var fs = require('fs')

const regions = {
    '东城区': '#a9f036',
    '丰台区': '#d14035',
    '大兴区': '#4b77ff',
    '密云区': '#8ab4ff',
    '平谷区': '#fe83c0',
    '延庆区': '#f9e8a2',
    '怀柔区': '#f39e8d',
    '房山区': '#ebd27b',
    '昌平区': '#71bac0',
    '朝阳区': '#bbd2bd',
    '海淀区': '#7ffb8d',
    '石景山区': '#93dea1',
    '西城区': '#a2c7b0',
    '通州区': '#ceb0b2',
    '门头沟区': '#f69bb4',
    '顺义区': '#9994d6'
}

const enDistrictMap = {
    '东城区': 'dongchengqu',
    '丰台区': 'fengtaiqu',
    '大兴区': 'daxingqu',
    '密云区': 'miyunqu',
    '平谷区': 'pingguqu',
    '延庆区': 'yanqingqu',
    '怀柔区': 'huairouqu',
    '房山区': 'fangshanqu',
    '昌平区': 'changpingqu',
    '朝阳区': 'chaoyangqu',
    '海淀区': 'haidianqu',
    '石景山区': 'shijingshanqu',
    '西城区': 'xichengqu',
    '通州区': 'tongzhouqu',
    '门头沟区': 'mentougouqu',
    '顺义区': 'shunyiqu'
}

const enRegionMap = {
    '东四十条.json': 'dongsishitiao.json',
    '东直门.json': 'dongzhimen.json',
    '北新桥_簋街.json': 'beixinqiao_guijie.json',
    '南锣古巷_鼓楼后海.json': 'nanluoguxiang_gulouhouhai.json',
    '和平里.json': 'hepingli.json',
    '天坛.json': 'tiantan.json',
    '天安门广场.json': 'tiananmenguangchang.json',
    '安定门.json': 'andingmen.json',
    '崇文门.json': 'chongwenmen.json',
    '左安门.json': 'zuoanmen.json',
    '广渠门.json': 'guangqumen.json',
    '建国门_北京站.json': 'jianguomen_beijingzhan.json',
    '朝阳门.json': 'zhaoyangmen.json',
    '沙子口.json': 'shazikou.json',
    '王府井_东单.json': 'wangfujing_dongdan.json',
    '王府井_前门.json': 'wangfujing_qianmen.json',
    '雍和宫.json': 'yonghegong.json',
    '丽泽桥_丰管路.json': 'lizeqiao_fengguanlu.json',
    '云岗.json': 'yungang.json',
    '分钟寺_成寿寺.json': 'fenzhongsi_chengshousi.json',
    '刘家窑_宋家庄.json': 'liujiayao_songjiazhuang.json',
    '北京南站_开阳里.json': 'beijingnanzhan_kaiyangli.json',
    '北京西站_六里桥.json': 'beijingxizhan_liuliqiao.json',
    '北大地_万丰路.json': 'beidade_wanfenglu.json',
    '南苑_东高地.json': 'nanyuan_donggaodi.json',
    '卢沟桥.json': 'lugouqiao.json',
    '夏家胡同_纪家庙.json': 'xiajiahutong_jijiamiao.json',
    '大红门.json': 'dahongmen.json',
    '方庄_蒲黄榆.json': 'fangzhuang_puhuangyu.json',
    '洋桥_木樨园.json': 'yangqiao_muxiyuan.json',
    '看丹桥_新华街.json': 'kandanqiao_xinhuajie.json',
    '花乡_新发地.json': 'huaxiang_xinfade.json',
    '草桥_公益西桥.json': 'caoqiao_gongyixiqiao.json',
    '青塔.json': 'qingta.json',
    '马家堡_角门.json': 'majiabao_jiaomen.json',
    '亦庄.json': 'yizhuang.json',
    '南苑机场_德茂桥.json': 'nanyuanjichang_demaoqiao.json',
    '庞各庄.json': 'panggezhuang.json',
    '旧宫.json': 'jiugong.json',
    '西红门.json': 'xihongmen.json',
    '黄村.json': 'huangcun.json',
    '司马台长城.json': 'simataizhangcheng.json',
    '密云县县城.json': 'miyunxianxiancheng.json',
    '密云水库.json': 'miyunshuiku.json',
    '桃源仙谷.json': 'taoyuanxiangu.json',
    '八达岭.json': 'badaling.json',
    '康庄.json': 'kangzhuang.json',
    '延庆城区.json': 'yanqingchengqu.json',
    '柳沟.json': 'liugou.json',
    '玉渡山风景区.json': 'yudushanfengjingqu.json',
    '百里画廊.json': 'bailihualang.json',
    '辉煌国际度假区.json': 'huihuangguojidujiaqu.json',
    '龙庆峡.json': 'longqingxia.json',
    '喇叭沟门白桦林景区.json': 'labagoumenbaihualinjingqu.json',
    '幽谷深潭.json': 'yougushentan.json',
    '怀北滑雪场.json': 'huaibeihuaxuechang.json',
    '怀柔城区.json': 'huairouchengqu.json',
    '怀柔电影旅游拍摄基地.json': 'huairoudianyinglvyoupaishejidi.json',
    '怀柔经济开发区.json': 'huairoujingjikaifaqu.json',
    '慕田峪长城.json': 'mutianyuchangcheng.json',
    '桥梓镇.json': 'qiaozizhen.json',
    '白河湾.json': 'baihewan.json',
    '神堂峪.json': 'shentangyu.json',
    '红螺寺.json': 'hongluosi.json',
    '莲花池.json': 'lianhuachi.json',
    '雁栖湖.json': 'yanqihu.json',
    '青龙峡.json': 'qinglongxia.json',
    '黄花城水长城.json': 'huanghuachengshuizhangcheng.json',
    '上方山国家森林公园.json': 'shangfangshanguojiasenlingongyuan.json',
    '十渡.json': 'shidu.json',
    '孤山寨.json': 'gushanzhai.json',
    '房山城关.json': 'fangshanchengguan.json',
    '河北镇.json': 'hebeizhen.json',
    '燕山.json': 'yanshan.json',
    '窦店.json': 'doudian.json',
    '良乡.json': 'liangxiang.json',
    '长阳镇.json': 'zhangyangzhen.json',
    '阎村.json': 'yancun.json',
    '北七家.json': 'beiqijia.json',
    '十三陵水库.json': 'shisanlingshuiku.json',
    '南口镇.json': 'nankouzhen.json',
    '回龙观.json': 'huilongguan.json',
    '天通苑.json': 'tiantongyuan.json',
    '小汤山镇.json': 'xiaotangshanzhen.json',
    '昌平镇.json': 'changpingzhen.json',
    '沙河.json': 'shahe.json',
    '三元桥.json': 'sanyuanqiao.json',
    '三里屯_工体.json': 'sanlitun_gongti.json',
    '东坝.json': 'dongba.json',
    '亚运村.json': 'yayuncun.json',
    '亮马桥.json': 'liangmaqiao.json',
    '传媒大学.json': 'chuanmeidaxue.json',
    '八里庄.json': 'balizhuang.json',
    '劲松.json': 'jingsong.json',
    '北京东站.json': 'beijingdongzhan.json',
    '北京欢乐谷.json': 'beijinghuanlegu.json',
    '北沙滩.json': 'beishatan.json',
    '北苑家园.json': 'beiyuanjiayuan.json',
    '十八里店.json': 'shibalidian.json',
    '十里河.json': 'shilihe.json',
    '双井.json': 'shuangjing.json',
    '双桥.json': 'shuangqiao.json',
    '和平里_国展中心.json': 'hepingli_guozhanzhongxin.json',
    '四惠东.json': 'sihuidong.json',
    '四惠交通枢纽.json': 'sihuijiaotongshuniu.json',
    '团结湖_朝阳公园.json': 'tuanjiehu_zhaoyanggongyuan.json',
    '国贸_建外.json': 'guomao_jianwai.json',
    '大屯.json': 'datun.json',
    '大望路.json': 'dawanglu.json',
    '太阳宫.json': 'taiyanggong.json',
    '孙河.json': 'sunhe.json',
    '安贞.json': 'anzhen.json',
    '对外经贸.json': 'duiwaijingmao.json',
    '小营.json': 'xiaoying.json',
    '左家庄.json': 'zuojiazhuang.json',
    '常营.json': 'changying.json',
    '建外大街.json': 'jianwaidajie.json',
    '望京.json': 'wangjing.json',
    '望京_善各庄.json': 'wangjing_shangezhuang.json',
    '朝外大街_世贸天阶.json': 'chaowaidajie_shimaotianjie.json',
    '朝阳公园.json': 'zhaoyanggongyuan.json',
    '朝阳大悦城.json': 'zhaoyangdayuecheng.json',
    '潘家园.json': 'panjiayuan.json',
    '王四营.json': 'wangsiying.json',
    '百子湾.json': 'baiziwan.json',
    '石佛营.json': 'shifuying.json',
    '立水桥_北苑家园.json': 'lishuiqiao_beiyuanjiayuan.json',
    '管庄.json': 'guanzhuang.json',
    '草房.json': 'caofang.json',
    '西直河_亦庄.json': 'xizhihe_yizhuang.json',
    '酒仙桥.json': 'jiuxianqiao.json',
    '首都机场.json': 'shoudujichang.json',
    '马泉营.json': 'maquanying.json',
    '高碑店.json': 'gaobeidian.json',
    '鸟巢_水立方.json': 'niaochao_shuilifang.json',
    '万柳.json': 'wanliu.json',
    '上地.json': 'shangde.json',
    '中关村.json': 'zhongguancun.json',
    '五棵松.json': 'wukesong.json',
    '五道口.json': 'wudaokou.json',
    '人民大学.json': 'renmindaxue.json',
    '公主坟_万寿路.json': 'gongzhufen_wanshoulu.json',
    '农业大学西区.json': 'nongyedaxuexiqu.json',
    '北下关.json': 'beixiaguan.json',
    '北京西站_军博.json': 'beijingxizhan_junbo.json',
    '双榆树.json': 'shuangyushu.json',
    '四季青.json': 'sijiqing.json',
    '大钟寺.json': 'dazhongsi.json',
    '学院路.json': 'xueyuanlu.json',
    '清河.json': 'qinghe.json',
    '牡丹园_北太平庄.json': 'mudanyuan_beitaipingzhuang.json',
    '百望山森林公园_309医院.json': 'baiwangshansenlingongyuan_309yiyuan.json',
    '知春路.json': 'zhichunlu.json',
    '紫竹桥.json': 'zizhuqiao.json',
    '航天桥.json': 'hangtianqiao.json',
    '颐和园.json': 'yiheyuan.json',
    '香山_植物园.json': 'xiangshan_zhiwuyuan.json',
    '八大处.json': 'badachu.json',
    '古城_八角.json': 'gucheng_bajiao.json',
    '模式口.json': 'moshikou.json',
    '苹果园.json': 'pingguoyuan.json',
    '鲁谷.json': 'lugu.json',
    '前门_大栅栏.json': 'qianmen_dazhalan.json',
    '前门_天坛.json': 'qianmen_tiantan.json',
    '右安门.json': 'youanmen.json',
    '后海_什刹海.json': 'houhai_shenshahai.json',
    '和平门.json': 'hepingmen.json',
    '宣武门.json': 'xuanwumen.json',
    '广内大街.json': 'guangneidajie.json',
    '广外大街.json': 'guangwaidajie.json',
    '德外大街.json': 'dewaidajie.json',
    '新街口.json': 'xinjiekou.json',
    '月坛.json': 'yuetan.json',
    '白纸坊.json': 'baizhifang.json',
    '菜市口_陶然亭.json': 'caishikou_taoranting.json',
    '西便门.json': 'xibianmen.json',
    '西单.json': 'xidan.json',
    '西四.json': 'xisi.json',
    '西直门_动物园.json': 'xizhimen_dongwuyuan.json',
    '金融街.json': 'jinrongjie.json',
    '阜成门.json': 'fuchengmen.json',
    '首都博物馆_莲花池东路.json': 'shoudubowuguan_lianhuachidonglu.json',
    '九棵树.json': 'jiukeshu.json',
    '八里桥.json': 'baliqiao.json',
    '土桥.json': 'tuqiao.json',
    '宋庄.json': 'songzhuang.json',
    '新华大街.json': 'xinhuadajie.json',
    '新华联.json': 'xinhualian.json',
    '梨园.json': 'liyuan.json',
    '次渠.json': 'ciqu.json',
    '武夷花园.json': 'wuyihuayuan.json',
    '通州北苑.json': 'tongzhoubeiyuan.json',
    '马驹桥.json': 'majuqiao.json',
    '妙峰山.json': 'miaofengshan.json',
    '潭柘寺.json': 'tanzhesi.json',
    '爨底下村.json': 'cuandixiacun.json',
    '门头沟城区.json': 'mentougouchengqu.json',
    '南彩镇.json': 'nancaizhen.json',
    '后沙峪.json': 'houshayu.json',
    '天竺.json': 'tianzhu.json',
    '小汤山_央美博艺艺术馆.json': 'xiaotangshan_yangmeiboyiyishuguan.json',
    '尺木无山.json': 'chimuwushan.json',
    '石园.json': 'shiyuan.json',
    '顺义城区.json': 'shunyichengqu.json',
    '首都机场T3航站楼.json': 'shoudujichangT3hangzhanlou.json',
    '首都机场_机场路.json': 'shoudujichang_jichanglu.json'
}

const regionNames = Object.keys(regions)


const districtRegionMap = {
    '东城区': ['东四十条.json', '东直门.json', '北新桥_簋街.json', '南锣古巷_鼓楼后海.json', '和平里.json', '天坛.json', '天安门广场.json', '安定门.json', '崇文门.json', '左安门.json', '广渠门.json', '建国门_北京站.json', '朝阳门.json', '沙子口.json', '王府井_东单.json', '王府井_前门.json', '雍和宫.json'],
    '丰台区': ['丽泽桥_丰管路.json', '云岗.json', '分钟寺_成寿寺.json', '刘家窑_宋家庄.json', '北京南站_开阳里.json', '北京西站_六里桥.json', '北大地_万丰路.json', '南苑_东高地.json', '卢沟桥.json', '夏家胡同_纪家庙.json', '大红门.json', '方庄_蒲黄榆.json', '洋桥_木樨园.json', '看丹桥_新华街.json', '花乡_新发地.json', '草桥_公益西桥.json', '青塔.json', '马家堡_角门.json'],
    '大兴区': ['亦庄.json', '南苑机场_德茂桥.json', '庞各庄.json', '旧宫.json', '西红门.json', '黄村.json'],
    '密云区': ['司马台长城.json', '密云县县城.json', '密云水库.json', '桃源仙谷.json'],
    '平谷区': [],
    '怀柔区': ['喇叭沟门白桦林景区.json', '幽谷深潭.json', '怀北滑雪场.json', '怀柔城区.json', '怀柔电影旅游拍摄基地.json', '怀柔经济开发区.json', '慕田峪长城.json', '桥梓镇.json', '白河湾.json', '神堂峪.json', '红螺寺.json', '莲花池.json', '雁栖湖.json', '青龙峡.json', '黄花城水长城.json'],
    '房山区': ['上方山国家森林公园.json', '十渡.json', '孤山寨.json', '房山城关.json', '河北镇.json', '燕山.json', '窦店.json', '良乡.json', '长阳镇.json', '阎村.json'],
    '昌平区': ['北七家.json', '十三陵水库.json', '南口镇.json', '回龙观.json', '天通苑.json', '小汤山镇.json', '昌平镇.json', '沙河.json'],
    '朝阳区': ['三元桥.json', '三里屯_工体.json', '东坝.json', '亚运村.json', '亮马桥.json', '传媒大学.json', '八里庄.json', '劲松.json', '北京东站.json', '北京欢乐谷.json', '北沙滩.json', '北苑家园.json', '十八里店.json', '十里河.json', '双井.json', '双桥.json', '和平里_国展中心.json', '四惠东.json', '四惠交通枢纽.json', '团结湖_朝阳公园.json', '国贸_建外.json', '大屯.json', '大望路.json', '太阳宫.json', '孙河.json', '安贞.json', '对外经贸.json', '小营.json', '左家庄.json', '常营.json', '建外大街.json', '望京.json', '望京_善各庄.json', '朝外大街_世贸天阶.json', '朝阳公园.json', '朝阳大悦城.json', '潘家园.json', '王四营.json', '百子湾.json', '石佛营.json', '立水桥_北苑家园.json', '管庄.json', '草房.json', '西直河_亦庄.json', '酒仙桥.json', '首都机场.json', '马泉营.json', '高碑店.json', '鸟巢_水立方.json'],
    '海淀区': ['万柳.json', '上地.json', '中关村.json', '五棵松.json', '五道口.json', '人民大学.json', '公主坟_万寿路.json', '农业大学西区.json', '北下关.json', '北京西站_军博.json', '双榆树.json', '四季青.json', '大钟寺.json', '学院路.json', '清河.json', '牡丹园_北太平庄.json', '百望山森林公园_309医院.json', '知春路.json', '紫竹桥.json', '航天桥.json', '颐和园.json', '香山_植物园.json'],
    '石景山区': ['八大处.json', '古城_八角.json', '模式口.json', '苹果园.json', '鲁谷.json'],
    '西城区': ['前门_大栅栏.json', '前门_天坛.json', '右安门.json', '后海_什刹海.json', '和平门.json', '宣武门.json', '广内大街.json', '广外大街.json', '德外大街.json', '新街口.json', '月坛.json', '白纸坊.json', '菜市口_陶然亭.json', '西便门.json', '西单.json', '西四.json', '西直门_动物园.json', '金融街.json', '阜成门.json', '首都博物馆_莲花池东路.json'],
    '通州区': ['九棵树.json', '八里桥.json', '土桥.json', '宋庄.json', '新华大街.json', '新华联.json', '梨园.json', '次渠.json', '武夷花园.json', '通州北苑.json', '马驹桥.json'],
    '延庆区' : ['八达岭.json', '康庄.json', '延庆城区.json', '柳沟.json', '玉渡山风景区.json', '百里画廊.json', '辉煌国际度假区.json', '龙庆峡.json'],
    '门头沟区': ['妙峰山.json', '潭柘寺.json', '爨底下村.json', '门头沟城区.json'],
    '顺义区': ['南彩镇.json', '后沙峪.json', '天竺.json', '小汤山_央美博艺艺术馆.json', '尺木无山.json', '石园.json', '顺义城区.json', '首都机场T3航站楼.json', '首都机场_机场路.json']
}

/*
{
    '海淀区' : ['万柳.json', '上地.json', '中关村.json', '五棵松.json', '五道口.json', '人民大学.json', '公主坟_万寿路.json', '农业大学西区.json', '北下关.json', '北京西站_军博.json', '双榆树.json', '四季青.json', '大钟寺.json', '学院路.json', '清河.json', '牡丹园_北太平庄.json', '百望山森林公园_309医院.json', '知春路.json', '紫竹桥.json', '航天桥.json', '颐和园.json', '香山_植物园.json'],
    '延庆区' : ['八达岭.json', '康庄.json', '延庆城区.json', '柳沟.json', '玉渡山风景区.json', '百里画廊.json', '辉煌国际度假区.json', '龙庆峡.json'],
    

}*/



const colorPool = ['#a9f036', '#d14035', '#4b77ff', '#8ab4ff', '#fe83c0', '#f9e8a2', '#f39e8d', '#ebd27b', '#71bac0', '#bbd2bd', '#7ffb8d', '#93dea1', '#a2c7b0', '#ceb0b2', '#f69bb4', '#9994d6', '#fddffd', '#bfe7ff', '#edbcee', '#8fcfdd', '#db8cd7', '#faffb0', '#cbffb0', '#b0ffd5', '#b0fffd', '#b0e5ff', '#847a18', '#5c6f7c', '#9e6614', '#944617', '#ff4000', '#207db6', '#f2c7f4', '#ff6700', '#23a546']


export {enDistrictMap, enRegionMap, regions, districtRegionMap, colorPool}